# Generated by Django 4.0 on 2022-01-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_user_email_alter_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉넥임입니다'}, max_length=15, null=True, unique=True, verbose_name='별명'),
        ),
    ]
