# Generated by Django 4.0.4 on 2022-05-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_user_email_alter_user_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
    ]
